title: SpongeBob Style
description: ""
encoding: utf-8

navigation:
  - title: Home
    url: /
  - title: Tonic
    url: https://tonic.hackclub.com
  - title: Dev
    url: /developer





exclude: ["README.md", "LICENSE", "*.gem", "*.gemspec", "Gemfile.lock"]